kkcreds = {
    ["Hearthstone Interface Assets"] = "©2014 Blizzard Entertainment, Inc. All rights reserved. Heroes of Warcraft is a trademark, and Hearthstone is a registered trademark of Blizzard Entertainment, Inc. in the U.S. and/or other countries.",
    ["World of Warcraft Interface Assets"] = "©2004 Blizzard Entertainment, Inc. All rights reserved. World of Warcraft, Warcraft and Blizzard Entertainment are trademarks or registered trademarks of Blizzard Entertainment, Inc. in the U.S. and/or other countries.",
    ["Open Source RPG Icons"] = "Ravenmore @ https://opengameart.org/",
    ["Hero Glow"] = "assasin_lord",
    ["Gold Ore, Silver Ore, Iron Ore"] = "Ergius",
    ["Pixel to DPI"] = "Quilnez/Kazeon",
    ["Devilsaur Pack, Genesaur"] = "Explobomb",
    ["Magnaron"] = "Maldiran",
    ["Confirmation"] = "Epsilon",
    ["Ground Explosion, Explosion Big, Sparks Explosion, Dirt Explosion"] = "WILL THE ALMIGHTY",
    ["Generic Canister, Orb Elements, Item Powerups"] = "General Frank",
    ["Lightning Strike, Blue/Green Fungus, Ratorg Rider, Void Lord"] = "Callahan",
    ["Orcish Runes"] = "frostwhisper",
    ["Purified Maw Giant"] = "Draconian",
    ["Naga Lord Pack"] = "Tier10Trash",
    ["Naga Brute Pack"] = "BardBord",
    ["Running Flame Aura"] = "sPy",
    ["Magic Shield"] = "JesusHipster",
    ["Simple White Bag"] = "Captain Bacon, ILH",
    ["Cannon Turret"] = "arnelbigstonepd33r",
    ["Troll Den, Gold Pile"] = "HerrDave",
    ["Global Init, Timer Utils"] = "Bribe",
    ["Arcing Text Tag"] = "Maker",
    ["Sleet Storm"] = "Hate",
    ["Kobold Slavemaster, Kobold Basher"] = "-Grendel",
    ["HQ Gold Chest"] = "HammerFist132",
    ["Kobold Stalker"] = "levigeorge1617",
    ["Kobold Hero"] = "Direfury",
    ["Rune Golem"] = "Alpain",
    ["Sentinel Shrine"] = "xYours Trulyx",
    ["Icon Model Packs"] = "Kenathorn",
    ["Bless"] = "Thrikodius",
    ["Candle"] = "bisnar13",
    ["Morgul Blade"] = "Uncle Fester",
    ["Nature Staff"] = "Blood Raven",
    ["Akama's Kama"] = "Systemfre1",
    ["Handheld Lantern"] = "smithyjones",
    ["Backpack"] = "dioris",
    ["Void Missiles, Void Rifts, Void Teleport, Fire Missiles, Conflagrate, Missile I, Missile II, Shot I, Shot II, Malevolence Aura, Pillar of Flame, Rain of Fire II, Judgement, "
    .."Ember, Storm Bolt, Soul Beam, Soul Armor, Runic Rocket, Singularity I, Singularity II, Righteous Guard, Uber Shield, Climax, Winder Blast, Blink I, Blizzard II, Bondage, "
    .."Flamestrike, Eldritch Scroll, Chain Grenade, Carrion Bats, Burning Rage, Athelas, Armor Pen/Stimulus, Firebrand Shots, Frostcraft Crystal, Psionic Shot, Heaven's Gate "
    .."Heal, Ice Shard, Sacred Storm, Shining Flare, Soul Armor, Soul Beam, Soul Discharge, Stormfall, Valiant Charge, Shock Blast, Windwalk, Reaper Claws, Starfall Empire"] = "Mythic",
}
